commitlint: resolve noUnusedParameters errors
The `ConvertAnyToString` fn has extra and unused parameters
that I had to remove:

```
commitlint/helpers.ts:21:9 - error TS6133: 'paramName' is declared but its value is never read.
```