CI: run commitlint tests outside of container
Commitlint fails to execute because a Git error is occurring
and it cannot recognize the Git repository:

```
Error: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

After investigating, I found out that when we run the
commitlint plugins tests job on a Docker container, there’s
no `.git` directory at all.