CI: configure git inside docker container
Commitlint fails to execute because a Git error is occurring
and it cannot recognize the Git repository:

```
Error: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Another workaround is to not use container in CI.