scripts: adding sanity check
The sanity check script requires the packages directory, so
i had to create this configuration file otherwise the
following error would occur:

```
Run dotnet fsi scripts/sanitycheck.fsx
8 nuget packages found for solution conventions.sln
System.Exception: 'packages' subdir under solution dir /__w/conventions/conventions/packages doesn't exist, run `make` first
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in /build/dotnet6-FDnqMS/dotnet6-6.0.123/src/fsharp/artifacts/source-build/self/src/src/fsharp/FSharp.Core/printf.fs:line 1439
   at FSI_0007.findMissingPackageDirs@244(DirectoryInfo solDir, FSharpMap`2 idealPackageDirs)
   at FSI_0007.sanityCheckNugetPackagesFromSolution@120(FileInfo sol)
   at FSI_0007.SanityCheckNugetPackages()
   at <StartupCode$FSI_0007>.$FSI_0007.main@()
Stopped due to error
Error: Process completed with exit code 1.
```